Events:
  Enabled: true
  MinPlayers: 5
  MaxPlayers: 0
  Delay: 1800
  Commands:
    1:
      Chance: 60
      RandomizeCommands: true
      Commands:
        - "bair start ordinary_dungeons_hiding"
        - "bair start ordinary_edge_storage"
        - "bair start ordinary_mystical_chest"
        - "bair start ordinary_nether_treasure"
        - "bair start ordinary_sea_treasure"
    2:
      Chance: 30
      RandomizeCommands: true
      Commands:
        - "bair start rare_dungeons_hiding"
        - "bair start rare_edge_storage"
        - "bair start rare_mystical_chest"
        - "bair start rare_nether_treasure"
        - "bair start rare_sea_treasure"
    3:
      Chance: 10
      RandomizeCommands: true
      Commands:
        - "bair start legendary_dungeons_hiding"
        - "bair start legendary_edge_storage"
        - "bair start legendary_mystical_chest"
        - "bair start legendary_nether_treasure"
        - "bair start legendary_sea_treasure"